### ISSUE TITLE
Criar conteudo do site (meio urgente)

### ISSUE THREAD

**Issue by PrieTorres** [PrieTorres/Estudas#19]
no momento o que temos é somente cursos para visualizar melhor como o site vai funcionar

teremos no total 8 cursos
- [x] Lógica de Programação
- [x] Linguagem de Programação C
- [x] Bibliotecas básicas em C
- [x] Declaração de variáveis
- [x] Comandos de Entrada e Saída
- [x] Condicional
- [x] Laços de Repetição

cada curso precisa conter 
- Textos;
- Infográficos;
- Vídeos;
- Imagens;
- Exercícios resolvidos (contendo o passo a passo);
- Exercícios para os alunos resolverem (incluindo exercícios dinâmicos como os de lógica do Racha Cuca, Hora do Código, entre outros).

para criação desse conteúdo podem utilizar word ou oq acharem melhor (extrema preferencia por HTML)
eu vou incluir no site depois

**Comment by GabrielHTissi** [comment]
comandos de entrada e saída e laços de repetição.

**Comment by Brunoxmgl** [comment]
Lógica de programação 
Linguagem de programaçao em C

**Comment by RenanGPie** [comment]
Bibliotecas básicas em C
Declaração de variáveis
