### ISSUE TITLE
melhorias gerais

### ISSUE THREAD

**Issue by PrieTorres** [PrieTorres/Estudas#23]
melhorias a serem feitas

- [x]  diminuir tamanho de imagens em tela desktop
- [x]  adicionar linha na tabela
- [x]  curso com pointer e animação de hover
- [x]  tradução de menu
- [x]  melhorar estilos mobile
- [x]  melhorar página home, incluir apresentação e deixar mais bonita

**Comment by PrieTorres** [comment]
alguns já foram ajustados no pr #24

**Comment by Brunoxmgl** [comment]
- (opcional) clicar no "Estudas" retorna ao home

- (opcional)  no header inverter o inicio com o cursos, deixando inicio/cursos/sobre nos

- (precisa fazer) no curso "Logica de programação" na etapa 4, no fim da conclusão, coloca `<a href="https://youtu.be/FF1wTboPbkc?si=2RxI1pPBdNyclzvB" target="_blank">Video: O que é Lógica de Programação | Duvido você não entender agora</a>
`
- (precisa fazer) no curso "linguagem de programação c", na segunda etapa, no final, tem um link "VIDEO PRA COLOCAR AI", muda o código pra `<a href="https://www.youtube.com/watch?v=6mUCcsnCn08" target="_blank">Video: C (A Linguagem de Programação que é uma MÃE) // Dicionário do Programador</a>` 

- (precisa fazer) ainda no curso linguagem de programação C, na questão 2 de 3 do quiz ta errado, só mudar o codigo ai pra esse :
     ```
   {
            "type": "quiz",
            "question": "Para que serve a funcao #include <stdio.h>?",
            "answer": "importar uma biblioteca de entrada e saída padrão.",
            "options": [
                "Importar um estúdio de entrada e saída padrão.",
                "importar uma biblioteca de entrada e saída padrão.",
                "Nenhuma das alternativas."
            ]
        },
```

- (nao sei se é obrigatorio) colocar os cursos na ordem que foi orientada no teams:
1-Lógica de Programação
2-Linguagem de Programação C
3-Bibliotecas básicas em C
4-Declaração de variáveis
5-Comandos de Entrada e Saída
6-Estruturas Condicionais
7-Laços de Repetição

- (opcional) quiz: talvez um botao de reiniciar o quiz e/ou mostrar qual era a resposta certa quando a pessoa errar

- (opcional) botão de finalizar curso, voltando pra aba cursos

-(opcional) Progressão de cursos (devia ter dado sugestões antes, malz): 
	atualmente: no inicio, tem os cursos em andamento, mostrando o % e o pendente.
		    na aba cursos, tem o nome do curso e "não iniciado".

	ideia 1 (possivelmente a mais complicada): juntar ambos na aba curso, removendo os cursos em andamento, e colocando o andamento direto em cada curso da aba cursos.
	por exemplo, ao invés de ter um "Bibliotecas em C - Não iniciado" na aba cursos, colocar direto "Bibliotecas em C- Pendente - 0%", mesclando as duas funçoes.

	ideia 2 (mais simples): só colocar os cursos em andamendo na aba dos cursos, acho que deixa a aba do home mais clean, só com a introduçao boas vindas/introduçao/instruçoes que vou fazer de noite 

Obs:
-revisei só os conteudos dos meus cursos, que precisa arrumar o que coloquei ali como "precisa fazer"
-os opcionais sao só algo que reparei e que eu mudaria, mas como somos uma equipe, podemos verificar com o resto ou vc decide 
-perdao pelo incomodo, vc puxou a responsa e lançou a braba, parabens pelo projeto, ficou pica. ¯\_(ツ)_/¯
